[project]
name = "mcp-lc"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "langchain-google-genai>=2.1.5",
    "langchain-groq>=0.3.2",
    "mcp-use>=1.3.0",
]
